name: "Build & Release All"

on:
  workflow_dispatch:

jobs:
  android:
    name: Android
    uses: ./.github/workflows/build-android.yml
    secrets: inherit

  windows:
    name: Windows
    uses: ./.github/workflows/build-windows.yml
    secrets: inherit

  linux:
    name: Linux
    uses: ./.github/workflows/build-linux.yml
    secrets: inherit
